very_low = 5
low=30
medium=55
high=80
very_high = 90

mazowiecka=very_high        #r1
krowoderska=low             #r2
zulawskiego=very_low        #r3
slaska=very_low             #r4
pradnicka1=very_high        #r6
pradnicka2=low              #r7
dluga1=low                  #r8
dluga2=low                  #r9
kamienna1=low               #r12
kamienna2=high              #r13
aleja29listopada1=medium    #16
aleja29listopada2=medium    #17
aleja29listopada3=medium    #20
aleja29listopada4=medium    #21
aleja29listopada5=medium    #25
aleja29listopada6=medium    #26
aleja29listopada7=medium    #27
aleja29listopada8=medium    #28
stwosza=low                 #30
stwosza2=low                #32
rakowicka1=high             #35
rakowicka2=high             #36
lubomirskiego1=medium       #39
lubomirskiego2=medium       #41